#!/usr/bin/perl -w
# Copyright (C) 2019 all contributors <meta@public-inbox.org>
# License: AGPL-3.0+ <https://www.gnu.org/licenses/agpl-3.0.txt>
# xcpdb: Xapian copy database, a wrapper around Xapian's copydatabase(1)
use PublicInbox::InboxWritable;
use PublicInbox::Xapcmd;
use PublicInbox::Admin;
PublicInbox::Admin::require_or_die('-search');
my $usage = "Usage: public-inbox-xcpdb INBOX_DIR\n";
my @ibxs = PublicInbox::Admin::resolve_inboxes(\@ARGV) or die $usage;
my $cmd = [ \&PublicInbox::Xapcmd::cpdb ];
open my $null, '>', '/dev/null' or die "failed to open /dev/null: $!\n";
my $rdr = { 1 => fileno($null) };
foreach (@ibxs) {
	my $ibx = PublicInbox::InboxWritable->new($_);
	# we rely on --no-renumber to keep docids synched to NNTP
	PublicInbox::Xapcmd::run($ibx, $cmd, undef, $rdr);
}
