#!/usr/bin/perl -w
# Copyright (C) 2015 all contributors <meta@public-inbox.org>
# License: AGPLv3 or later (https://www.gnu.org/licenses/agpl-3.0.txt)
#
# Standalone NNTP server for public-inbox.
use strict;
use warnings;
require PublicInbox::Daemon;
require PublicInbox::NNTP;
require PublicInbox::NNTPD;
my $nntpd = PublicInbox::NNTPD->new;
PublicInbox::Daemon::run('0.0.0.0:119',
	sub { $nntpd->refresh_groups }, # refresh
	sub ($$$) { PublicInbox::NNTP->new($_[0], $nntpd) }); # post_accept
