#!/usr/bin/perl -w
# Copyright (C) 2016 all contributors <meta@public-inbox.org>
# License: AGPL-3.0+ <https://www.gnu.org/licenses/agpl-3.0.txt>
use strict;
use warnings;
use PublicInbox::WatchMaildir;
use PublicInbox::Config;
my ($config, $watch_md);
my $reload = sub {
	$config = PublicInbox::Config->new;
	$watch_md = PublicInbox::WatchMaildir->new($config);
};
$reload->();
if ($watch_md) {
	my $scan = sub { $watch_md->scan if $watch_md };
	$SIG{HUP} = $reload;
	$SIG{USR1} = $scan;
	$SIG{ALRM} = sub { $SIG{ALRM} = 'DEFAULT'; $scan->() };
	alarm(1);
	$watch_md->watch;
}
