#!perl -w
# Copyright (C) 2020 all contributors <meta@public-inbox.org>
# License: AGPL-3.0+ <https://www.gnu.org/licenses/agpl-3.0.txt>
#
# Standalone read-only IMAP server for public-inbox.
use strict;
use PublicInbox::Daemon;
use PublicInbox::IMAPdeflate; # loads PublicInbox::IMAP
use PublicInbox::IMAPD;
my $imapd = PublicInbox::IMAPD->new;
PublicInbox::Daemon::run('0.0.0.0:143',
	sub { $imapd->refresh_groups }, # refresh
	sub ($$$) { PublicInbox::IMAP->new($_[0], $imapd) }, # post_accept
	$imapd);
