=head1 NAME

lei-lcat - display local copy of messages(s)

=head1 SYNOPSIS

lei lcat [OPTIONS] MSGID_OR_URL [MSGID_OR_URL...]

lei lcat [OPTIONS] (--stdin|-)

=head1 DESCRIPTION

lcat (local cat) is a wrapper around L<lei-q(1)> that displays local
messages by Message-ID.  It is able to extract Message-IDs from URLs
as well as from common formats such as C<E<lt>$MSGIDE<gt>> and
C<id:$MSGID>.  When reading from stdin, input that isn't understood is
discarded, so the caller doesn't have to bother extracting the
Message-ID or link from surrounding text (e.g., a "Link: $URL" line).

=head1 OPTIONS

The following options, described in L<lei-q(1)>, are supported.
One deviation from L<lei-q(1)> is the default output format is
C<-f text> when writing to stdout.

=over

=item --format=FORMAT

=item -f FORMAT

Most commonly C<text> (the default) or C<reply> to
display the message(s) in a format suitable for trimming
and sending as a email reply.

=item --stdin

=item -

C<lei lcat> implicitly reads from stdin if it is a L<pipe(7)>
or regular file.  This is handy for invoking C<lei lcat> from
inside an C<$EDITOR> session (assuming you use an C<$EDITOR>
which lets you pipe arbitrary lines to arbitrary commands).

=item --[no-]remote

=item --no-local

=item --no-external

=item --no-import-remote

=item --torsocks=auto|no|yes, --no-torsocks

=item --proxy=PROTOCOL://HOST[:PORT]

=item -o MFOLDER, --output=MFOLDER

=item -d STRATEGY, --dedupe=STRATEGY

=item -t, --threads

=item -s KEY, --sort=KEY

=item -r, --reverse

=item --offset=NUMBER

=item -g, --globoff

=item -a, --augment

=item --lock=METHOD

=item --alert=COMMAND

=item --mua=COMMAND

=item --no-color

=back

=head1 CONTACT

Feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<https://public-inbox.org/meta/>
and L<http://4uok3hntl7oi7b4uf4rtfwefqeexfzil2w6kgk2jn5z2f764irre7byd.onion/meta/>

=head1 COPYRIGHT

Copyright 2021 all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<https://www.gnu.org/licenses/agpl-3.0.txt>

=head1 SEE ALSO

L<lei-q(1)>, L<lei-blob(1)>
