=head1 NAME

lei-inspect - general purpose inspector

=head1 SYNOPSIS

lei inspect [OPTIONS] ITEM [ITEM...]

lei inspect [OPTIONS] (--stdin|-)

=head1 DESCRIPTION

This is a diagnostic command that provides a general purpose inspector
of various things, including blobs, message IDs, Xapian document IDs,
and mail sync sources.

=head1 OPTIONS

=over

=item -d DIR

=item --dir=DIR

An inboxdir, extindex topdir, or Xapian shard

=item --pretty

Pretty print output.  If stdout is opened to a tty, C<--pretty> is
enabled by default.

=item -

=item --stdin

Read message from stdin.  This is implicit if no arguments are given
and stdin is a pipe or regular file.

=back

=head1 CONTACT

Feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<https://public-inbox.org/meta/> and
L<http://4uok3hntl7oi7b4uf4rtfwefqeexfzil2w6kgk2jn5z2f764irre7byd.onion/meta/>

=head1 COPYRIGHT

Copyright 2021 all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<https://www.gnu.org/licenses/agpl-3.0.txt>


=head1 SEE ALSO

L<lei-mail-diff(1)>
