=head1 NAME

lei-blob - display a git blob, reconstructing from mail if necessary

=head1 SYNOPSIS

lei blob [OPTIONS] OID

=head1 DESCRIPTION

Display a git blob.  The blob may correspond to a message from the
local store, any local external, or blobs associated with a
project git repository (if run from a git (working) directory).
For blobs which do not exist, it will attempt to recreate the blob
using patch emails.

=head1 OPTIONS

=over

=item --git-dir=DIR

Specify an additional .git/ directory to scan.  This option may be
given multiple times.

Default: the output of C<git rev-parse --git-dir>

=item --no-cwd

Do not look in the git repository of the current working directory.

=item --no-mail

Do not look in mail storage for C<OID>.  This is implied by
C<--oid-a>, C<--path-a>, and C<--path-b>.

=item -A OID-A

=item --oid-a=OID-A

Provide pre-image object ID as a hint for reconstructing C<OID>.

=item -a PATH-A

=item --path-a=PATH-A

Provide pre-image pathname as a hint for reconstructing C<OID>.

=item -b PATH-B

=item --path-b=PATH-B

Provide post-image pathname as a hint for reconstructing C<OID>.

=item -v

=item --verbose

Provide more feedback on stderr.

=back

The following options are also supported and are described in
L<lei-q(1)>.

=over

=item --remote

Remote externals only get queried when the blob needs to be
reconstructed from patch emails.

=item --no-local

=item --no-external

=item -I LOCATION, --include=LOCATION

=item --exclude=LOCATION

=item --only=LOCATION

=item --no-import-remote

=item --torsocks=auto|no|yes

=item --no-torsocks

=item --proxy=PROTO://HOST[:PORT]

=back

=head1 CONTACT

Feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<https://public-inbox.org/meta/> and
L<http://4uok3hntl7oi7b4uf4rtfwefqeexfzil2w6kgk2jn5z2f764irre7byd.onion/meta/>

=head1 COPYRIGHT

Copyright 2021 all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<https://www.gnu.org/licenses/agpl-3.0.txt>


=head1 SEE ALSO

L<lei-add-external(1)>, L<lei-q(1)>
