=head1 NAME

lei-forget-search - forget saved search

=head1 SYNOPSIS

lei forget-search [OPTIONS] OUTPUT

=head1 DESCRIPTION

Forget a saved search at C<OUTPUT>.

=head1 OPTIONS

=over

=item --prune[=<local|remote>]

C<--prune> will forget saved searches if the C<OUTPUT> no longer
exists.  C<--prune=local> only prunes local mailboxes,
C<--prune=remote> only prunes remote mailboxes (currently
C<imap://> and C<imaps://>).

=back

=head1 CONTACT

Feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<https://public-inbox.org/meta/>
and L<http://4uok3hntl7oi7b4uf4rtfwefqeexfzil2w6kgk2jn5z2f764irre7byd.onion/meta/>

=head1 COPYRIGHT

Copyright 2021 all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<https://www.gnu.org/licenses/agpl-3.0.txt>

=head1 SEE ALSO

L<lei-edit-search(1)>, L<lei-ls-search(1)>, L<lei-up(1)>, L<lei-q(1)>
