=head1 NAME

lei-convert - one-time conversion from one mail format to another

=head1 SYNOPSIS

lei convert -o OUTPUT [OPTIONS] LOCATION

lei convert -o OUTPUT [OPTIONS] (--stdin|-)

=head1 DESCRIPTION

Convert messages to another format.  C<LOCATION> is a source of
messages: a directory (Maildir), a file (various mbox), or a URL
(C<imap://>, C<imaps://>, C<nntp://>, or C<nntps://>).  URLs
requiring authentication use L<git-credential(1)> to
fill in the username and password.

For a regular file, the location must have a C<E<lt>formatE<gt>:>
prefix specifying one of the following formats: C<mboxrd>,
C<mboxcl2>, C<mboxcl>, or C<mboxo>.

=head1 OPTIONS

=over

=item -F MAIL_FORMAT

=item --in-format=MAIL_FORMAT

Message input format.  Unless messages are given on stdin, using a
format prefix with C<LOCATION> is preferred.

=back

The following options are also supported and are described in
L<lei-q(1)>.

=over

=item -o MFOLDER, --output=MFOLDER

=item --lock METHOD

=item --no-kw

=item --torsocks=auto|no|yes

=item --no-torsocks

=item --proxy=PROTO://HOST[:PORT]

=back

=head1 CONTACT

Feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<https://public-inbox.org/meta/>
and L<http://4uok3hntl7oi7b4uf4rtfwefqeexfzil2w6kgk2jn5z2f764irre7byd.onion/meta/>

=head1 COPYRIGHT

Copyright all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<https://www.gnu.org/licenses/agpl-3.0.txt>

=head1 SEE ALSO

L<lei-mail-formats(5)>
