=head1 NAME

lei-forget-external - forget external locations

=head1 SYNOPSIS

lei forget-external [OPTIONS] URL_OR_PATHNAME [URL_OR_PATHNAME...]

=head1 DESCRIPTION

Forget the specified externals by removing their entries from
C<$XDG_CONFIG_HOME/lei/config>.  This excludes the locations from
future search results.

=head1 OPTIONS

=over

=item -q, --quiet

Suppress feedback messages.

=back

=head1 CONTACT

Feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<https://public-inbox.org/meta/>
and L<http://hjrcffqmbrq6wope.onion/meta/>

=head1 COPYRIGHT

Copyright 2021 all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<https://www.gnu.org/licenses/agpl-3.0.txt>

=head1 SEE ALSO

L<lei-add-external(1)>, L<lei-ls-external(1)>
