=head1 NAME

lei-add-watch - watch for new messages and flag changes

=head1 SYNOPSIS

lei add-watch [OPTIONS] LOCATION [LOCATION...]

=head1 DESCRIPTION

Tell lei to watch C<LOCATION> for new messages and flag changes.
Currently only Maildir locations are supported.

WARNING: watches are not always reliable, occasional use
of L<lei-index(1)> and L<lei-refresh-mail-sync(1)> is recommended
if L<lei-daemon(8)> crashes or needs to be restarted.  This will
be improved in the future.

=for comment
TODO: Document --state?  Believe valid values are pause, import-ro,

=head1 CONTACT

Feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<https://public-inbox.org/meta/> and
L<http://4uok3hntl7oi7b4uf4rtfwefqeexfzil2w6kgk2jn5z2f764irre7byd.onion/meta/>

=head1 COPYRIGHT

Copyright all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<https://www.gnu.org/licenses/agpl-3.0.txt>

=head1 SEE ALSO

L<lei-ls-watch(1)>, L<lei-rm-watch(1)>
