=head1 NAME

public-inbox-mda - mail delivery for public-inbox

=head1 SYNOPSIS

B<public-inbox-mda> E<lt> message

=head1 DESCRIPTION

Mail Delivery Agent (MDA) for public-inbox installations.
Each system user may have their own public-inbox instances

=head1 ENVIRONMENT

=over 8

=item ORIGINAL_RECIPIENT

the original recipient email address, from Postfix

=item PI_CONFIG

config file. default: ~/.public-inbox/config

=item PI_EMERGENCY

emergency destination.  default: ~/.public-inbox/emergency/

=back

=head1 PI_CONFIG FILE

This is a config file parseable by L<git-config(1)>.

=head1 CONTACT

All feedback welcome via plain-text mail to L<mailto:meta@public-inbox.org>

The mail archives are hosted at L<http://public-inbox.org/meta/>

=head1 COPYRIGHT

Copyright 2013-2016 all contributors L<mailto:meta@public-inbox.org>

License: AGPL-3.0+ L<http://www.gnu.org/licenses/agpl-3.0.txt>

=head1 SEE ALSO

L<git(1)>, L<git-config(1)>, L<ssoma_repository(5)>
